-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgbMQbR8QKDSY0MG2M
jMfeB2sVMGoYswTzf/cE2YUqN7SgCgYIKoZIzj0DAQehRANCAASzoQcc/OMVDrb/
Z/JUMXj+46aY5biNkbGVTviCSQfyw5+EWHKgLRMVswnEImihPvfXnmDQGfs+ve8/
N8qlKkOk
-----END PRIVATE KEY-----